config/routes.rb
Rails.application.routes.draw do
  resources :galleries

  devise_for :users
  resources :publishers

  resources :widgets

  resources :book_templates

  resources :books

  resources :gallery_images

  get '/configurate/:id', to: 'book_configuration#configurate'
  get '/convert/:id', to: 'book_configuration#convert'
  get '/build/:id', to: 'book_configuration#build'
  get '/upload/:id', to: 'book_configuration#upload'

  get '/configurate/save/:id', to: 'book_configuration#save'

  root 'books#index'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<h1>Listing publishers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>