config/routes.rb
Rails.application.routes.draw do
  resources :galleries

  devise_for :users
  resources :publishers

  resources :widgets

  resources :book_templates

  resources :books

  resources :gallery_images

  get '/configurate/:id', to: 'book_configuration#configurate'
  get '/convert/:id', to: 'book_configuration#convert'
  get '/build/:id', to: 'book_configuration#build'
  get '/upload/:id', to: 'book_configuration#upload'

  get '/configurate/save/:id', to: 'book_configuration#save'

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :widgets

end

app/controllers/books_controller.rb
require 'pdf/reader'

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.order("title").page(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        
        save_file

        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)

        save_file

        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      
      FileUtils.rm_r(generate_book_files_path, {force: true})

      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :book_template)
    end

    def save_file
      principal_file = params[:book][:principal]
        
      full_path = FileUtils.mkdir_p (generate_book_files_path)
      file_name = 'book.pdf'

      file_path = Rails.root.join(full_path[0], file_name)
      File.open(file_path, 'wb') do |file|
        file.write(principal_file.read)
      end

      attachment_file = params[:book][:attachment]

      if attachment_file
        attachment_path = Rails.root.join(full_path[0], 'attachment.pdf')
        File.open(attachment_path, 'wb') do |file|
          file.write(attachment_file.read)
        end
      end

      pdf_reader = PDF::Reader.new(file_path)

      @book.update({file_path: file_path.to_s, 
                    total_pages: pdf_reader.page_count,
                    metadata: pdf_reader.metadata,
                    pdf_version: pdf_reader.pdf_version,
                    attachment_path: attachment_path.to_s})
    end

    def generate_book_files_path
      Rails.root.join('public', 'books', @book.id.to_s )
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :book_template, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :book_template, BookTemplate.all, :title, :title, prompt: true, :class => 'select_field' %>
      <%= link_to 'add', new_book_path, :class => 'btn btn-add' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :principal, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :principal, :class => 'btn-file', accept: 'application/pdf' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :attachment, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :attachment, :class => 'btn-file', accept: 'application/pdf' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:book_template) %></th>
      <th><%= model_class.human_attribute_name(:total_pages) %></th>
      <th><%= model_class.human_attribute_name(:pdf_version) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.book_template %></td>
        <td><%= book.total_pages %></td>
        <td><%= book.pdf_version %></td>
        <td><%=l book.created_at.to_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_book_path(book), :class => 'btn btn-mini' %>
          <%= link_to 'Config',
            "/configurate/#{book.id}",
            :method => :get,
            :class => 'btn btn-mini' %>
          <%= link_to 'Build', "/build/#{book.id}", :class => 'btn btn-mini' %>
          <%= link_to 'Build & Upload', "/upload/#{book.id}", :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            book_path(book),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @books %> 

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @book.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:book_template) %>:</strong></dt>
  <dd><%= @book.book_template %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_pages) %>:</strong></dt>
  <dd><%= @book.total_pages %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pdf_version) %>:</strong></dt>
  <dd><%= @book.pdf_version %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:resolution) %>:</strong></dt>
  <dd><%= @book.default_width %> x <%= @book.default_height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file_path) %>:</strong></dt>
  <dd><%= @book.file_path %></dd>
  
  <% unless @book.attachment_path.empty? %>
    <dt><strong><%= model_class.human_attribute_name(:attachment_path) %>:</strong></dt>
    <dd><%= @book.attachment_path %></dd>
  <% end %>
  
  <% unless @book.metadata == nil || @book.metadata.empty? %>
    <dt><strong><%= model_class.human_attribute_name(:metadata) %>:</strong></dt>
    <dd><%= @book.metadata %></dd>
  <% end %>

  <% unless @book.images_path == nil || @book.images_path.empty? %>
    <dt><strong><%= model_class.human_attribute_name(:images_path) %>:</strong></dt>
    <dd><%= @book.images_path %></dd>
  <% end %>

  <% unless @book.temp_link == nil || @book.temp_link.empty? %>
    <dt><strong><%= model_class.human_attribute_name(:temp_link) %>:</strong></dt>
    <dd><%= link_to 'download link', @book.temp_link %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <%= link_to 'Convert', "/convert/#{@book.id}", :class => 'btn btn-primary' %>
</div>