config/routes.rb
Rails.application.routes.draw do
  resources :galleries

  devise_for :users
  resources :publishers

  resources :widgets

  resources :book_templates

  resources :books

  resources :gallery_images

  get '/configurate/:id', to: 'book_configuration#configurate'
  get '/convert/:id', to: 'book_configuration#convert'
  get '/build/:id', to: 'book_configuration#build'
  get '/upload/:id', to: 'book_configuration#upload'

  get '/configurate/save/:id', to: 'book_configuration#save'

  root 'books#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :book
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :book_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :book_name %><br>
    <%= f.collection_select :book_id, Book.all, :id, :title, prompt: true, :class => 'select_field' %>
  </div>

      <div class="actions">


    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/_form_images.html.erb
<form action="/gallery_images" id="image-dropzone" class="dropzone" enctype="multipart/form-data">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <div class="fallback">
    
  </div>
</form>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>
<%= render 'form_images' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<%- model_class = Gallery -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:book_title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= link_to gallery.name, gallery_path(gallery) %></td>
        <td><%= link_to gallery.book.title, book_path(gallery.book) %><%= %></td>
        <td><%=l gallery.created_at.to_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gallery_path(gallery), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gallery_path(gallery),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gallery_path,
            :class => 'btn btn-primary' %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>
<%= render 'form_images' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<%- model_class = Gallery -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @gallery.name %></dd>

  <dt><strong><%= model_class.human_attribute_name(:book_title) %>:</strong></dt>
  <dd><%= @gallery.book.title %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), galleries_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_gallery_path(@gallery), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gallery_path(@gallery),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>